import { about, cases, faq, posts, solutions, technology, type CaseItem, type Language } from "./site-content";
import { CaseExplorer } from "./case-explorer";
import { ContactBand, PageTop, SiteFooter } from "./site-frame";

const Arrow=()=> <span aria-hidden="true">↗</span>;

export function SolutionsPage({lang}:{lang:Language}){const t=solutions[lang];const pt=lang==="pt";return <main lang={t.locale}><PageTop lang={lang} current={pt?"/solucoes":"/en/solutions"} overline={t.overline} title={t.title} intro={t.intro}/><section className="solution-index section-pad">{t.items.map(item=><article id={item.key} key={item.key}><header><span>{item.number}</span><h2>{item.title}</h2><p>{item.promise}</p></header><div><div><b>{pt?"QUANDO FAZ SENTIDO":"WHEN IT FITS"}</b>{item.problems.map(x=><p key={x}>{x}</p>)}</div><div><b>{pt?"O QUE PODE SER MOBILIZADO":"WHAT MAY BE MOBILIZED"}</b>{item.deliveries.map(x=><p key={x}>{x}</p>)}</div></div></article>)}</section><section className="process-band inverse section-pad"><p className="section-tag">RARVOR / {pt?"MÉTODO":"METHOD"}</p><div>{t.process.map(([title,copy],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section><ContactBand lang={lang}/><SiteFooter lang={lang}/></main>}

export function TechnologyPage({lang}:{lang:Language}){const t=technology[lang];const pt=lang==="pt";return <main lang={t.locale}><PageTop lang={lang} current={pt?"/tecnologia":"/en/technology"} overline={t.overline} title={t.title} intro={t.intro}/><section className="tech-principles section-pad">{t.principles.map(([title,copy],i)=><article key={title}><span>0{i+1}</span><h2>{title}</h2><p>{copy}</p></article>)}</section><section className="os-system inverse section-pad"><div><p className="section-tag">RARVOR OS / {pt?"ARQUITETURA":"ARCHITECTURE"}</p><h2>{pt?"Um sistema que conecta decisão, operação e aprendizado.":"A system connecting decisions, operations and learning."}</h2><p>{t.note}</p></div><div className="os-map">{t.systems.map((x,i)=><span key={x}><b>{String(i+1).padStart(2,"0")}</b>{x}</span>)}</div></section><section className="os-flow section-pad"><p className="section-tag">{pt?"FLUXO DE INTELIGÊNCIA":"INTELLIGENCE FLOW"}</p><div>{t.flow.map((x,i)=><span key={x}>{x}{i<t.flow.length-1&&<b>→</b>}</span>)}</div><p>{pt?"Tecnologia amplia julgamento. Decisão relevante continua humana, rastreável e responsável.":"Technology expands judgment. Relevant decisions remain human, traceable and accountable."}</p></section><ContactBand lang={lang}/><SiteFooter lang={lang}/></main>}

export function CasesPage({lang}:{lang:Language}){const t=cases[lang];const pt=lang==="pt";return <main lang={t.locale}><PageTop lang={lang} current={pt?"/cases":"/en/cases"} overline={t.overline} title={t.title} intro={t.intro}/><CaseExplorer items={t.items} lang={lang}/><p className="case-disclaimer section-pad">{t.note}</p><ContactBand lang={lang}/><SiteFooter lang={lang}/></main>}

export function CaseDetailPage({lang,item}:{lang:Language;item:CaseItem}){const pt=lang==="pt";const base=pt?"":"/en";return <main lang={pt?"pt-BR":"en"}><PageTop lang={lang} current={base+"/cases"} overline={`${item.index} / ${item.sector} / ${item.challenge}`} title={item.title} intro={item.summary}/><section className="case-detail section-pad"><aside><span>{item.status}</span><strong>{item.metric}</strong><p>{item.signal}</p>{item.ecosystem&&<em>{item.ecosystem}</em>}<a href={base+"/cases"}>← {pt?"Todos os cases":"All cases"}</a></aside><div><section><b>{pt?"CONTEXTO":"CONTEXT"}</b><p>{item.context}</p></section><section><b>{pt?"LEITURA":"READING"}</b><p>{item.reading}</p></section><section><b>{pt?"MOVIMENTO":"MOVEMENT"}</b><ol>{item.movement.map(x=><li key={x}>{x}</li>)}</ol></section><section className="case-evidence"><b>{pt?"EVIDÊNCIAS":"EVIDENCE"}</b>{item.evidence.map(x=><p key={x}>{x}</p>)}</section><section><b>{pt?"CAPACIDADES CRIADAS":"CAPABILITIES BUILT"}</b><div className="asset-tags">{item.assets.map(x=><span key={x}>{x}</span>)}</div></section><section className="case-limit"><b>{pt?"LIMITE DE ATRIBUIÇÃO":"ATTRIBUTION LIMIT"}</b><p>{item.limit}</p></section></div></section><ContactBand lang={lang}/><SiteFooter lang={lang}/></main>}

export function AboutPage({lang}:{lang:Language}){const t=about[lang];const pt=lang==="pt";return <main lang={t.locale}><PageTop lang={lang} current={pt?"/sobre":"/en/about"} overline={t.overline} title={t.title} intro={t.intro}/><section className="about-lead section-pad"><div className="founder-mark">RD</div><div><p className="section-tag">ROMULO DUGONI / STRATEGIC ADVISOR</p><h2>{t.thesis}</h2><p>{t.bio}</p></div></section><section className="timeline section-pad"><p className="section-tag">{pt?"TRAJETÓRIA / SISTEMA":"TRAJECTORY / SYSTEM"}</p>{t.timeline.map(([title,copy],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</section><section className="values inverse section-pad"><p className="section-tag">{pt?"PRINCÍPIOS":"PRINCIPLES"}</p><div>{t.values.map(([title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></section><ContactBand lang={lang}/><SiteFooter lang={lang}/></main>}

export function EssencePage({lang}:{lang:Language}){return <AboutPage lang={lang}/>}

export function FaqPage({lang}:{lang:Language}){const t=faq[lang];const pt=lang==="pt";const all=t.groups.flatMap(g=>g.items);const schema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:all.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))};return <main lang={t.locale}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><PageTop lang={lang} current={pt?"/faq":"/en/faq"} overline={t.overline} title={t.title} intro={t.intro}/><section className="faq-index section-pad"><aside><p className="section-tag">RARVOR / {pt?"RESPOSTAS":"ANSWERS"}</p><strong>{pt?"Clareza antes do compromisso.":"Clarity before commitment."}</strong></aside><div>{t.groups.map(group=><section className="faq-group" key={group.title}><h2>{group.title}</h2>{group.items.map(([question,answer],i)=><details key={question}><summary><span>{String(i+1).padStart(2,"0")}</span><strong>{question}</strong><i/></summary><p>{answer}</p></details>)}</section>)}</div></section><ContactBand lang={lang}/><SiteFooter lang={lang}/></main>}

export function BlogPage({lang}:{lang:Language}){const data=posts[lang];const pt=lang==="pt";return <main lang={pt?"pt-BR":"en"}><PageTop lang={lang} current={pt?"/blog":"/en/insights"} overline="INSIGHTS / 03" title={pt?"Ideias para compreender o que está em jogo.":"Ideas to understand what is at stake."} intro={pt?"Estratégia, negócios e tecnologia sem ruído.":"Strategy, business and technology without noise."}/><section className="blog-index section-pad">{data.map((post,i)=><a className={i===0?"featured":""} href={(pt?"/blog/":"/en/insights/")+post.slug} key={post.slug}><span>{post.category} · {post.date}</span><h2>{post.title}</h2><p>{post.excerpt}</p><strong>{post.read} ↗</strong></a>)}</section><SiteFooter lang={lang}/></main>}

export function ArticlePage({lang,slug}:{lang:Language;slug:string}){const post=posts[lang].find(x=>x.slug===slug);if(!post)return null;const pt=lang==="pt";return <main lang={pt?"pt-BR":"en"}><PageTop lang={lang} current={pt?"/blog":"/en/insights"} overline={`${post.category} / ${post.date}`} title={post.title} intro={post.excerpt}/><article className="article-body section-pad"><aside><span>{post.read}</span><a href={pt?"/blog":"/en/insights"}>← {pt?"Voltar":"Back"}</a></aside><div><p className="article-lead">{post.lead}</p>{post.paragraphs.map(p=><p key={p}>{p}</p>)}<blockquote>{pt?"Clareza não simplifica o problema. Torna o próximo movimento possível.":"Clarity makes the next movement possible."}</blockquote></div></article><ContactBand lang={lang}/><SiteFooter lang={lang}/></main>}
